# Generated by Django 4.1.4 on 2022-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=8)),
                ('equipa', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='AlunoTest',
        ),
    ]
